# Generated by Django 5.1.1 on 2024-10-27 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_feedback_question_10_feedback_question_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='feedback',
            field=models.TextField(default='No feedback provided'),
        ),
    ]
