# Generated by Django 5.1.1 on 2024-10-27 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_complaints_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
