# Generated by Django 5.1.1 on 2024-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_delete_complaints_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('complaint', 'Complaint'), ('compliment', 'Compliment')], default='feedback', max_length=20),
        ),
    ]
