# Generated by Django 5.1.1 on 2024-12-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_delete_complaints_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='compliment_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
